/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SaveQuery {
    }
}
declare global {
    interface HTMLSaveQueryElement extends Components.SaveQuery, HTMLStencilElement {
    }
    var HTMLSaveQueryElement: {
        prototype: HTMLSaveQueryElement;
        new (): HTMLSaveQueryElement;
    };
    interface HTMLElementTagNameMap {
        "save-query": HTMLSaveQueryElement;
    }
}
declare namespace LocalJSX {
    interface SaveQuery {
    }
    interface IntrinsicElements {
        "save-query": SaveQuery;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "save-query": LocalJSX.SaveQuery & JSXBase.HTMLAttributes<HTMLSaveQueryElement>;
        }
    }
}
