/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StaticFilter {
        "caption": string;
        "expression": string;
    }
}
declare global {
    interface HTMLStaticFilterElement extends Components.StaticFilter, HTMLStencilElement {
    }
    var HTMLStaticFilterElement: {
        prototype: HTMLStaticFilterElement;
        new (): HTMLStaticFilterElement;
    };
    interface HTMLElementTagNameMap {
        "static-filter": HTMLStaticFilterElement;
    }
}
declare namespace LocalJSX {
    interface StaticFilter {
        "caption": string;
        "expression": string;
    }
    interface IntrinsicElements {
        "static-filter": StaticFilter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "static-filter": LocalJSX.StaticFilter & JSXBase.HTMLAttributes<HTMLStaticFilterElement>;
        }
    }
}
