/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddToCart {
        "callbackFunction": string;
    }
}
declare global {
    interface HTMLAddToCartElement extends Components.AddToCart, HTMLStencilElement {
    }
    var HTMLAddToCartElement: {
        prototype: HTMLAddToCartElement;
        new (): HTMLAddToCartElement;
    };
    interface HTMLElementTagNameMap {
        "add-to-cart": HTMLAddToCartElement;
    }
}
declare namespace LocalJSX {
    interface AddToCart {
        "callbackFunction"?: string;
    }
    interface IntrinsicElements {
        "add-to-cart": AddToCart;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-to-cart": LocalJSX.AddToCart & JSXBase.HTMLAttributes<HTMLAddToCartElement>;
        }
    }
}
