/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QuickviewComponent {
    }
}
declare global {
    interface HTMLQuickviewComponentElement extends Components.QuickviewComponent, HTMLStencilElement {
    }
    var HTMLQuickviewComponentElement: {
        prototype: HTMLQuickviewComponentElement;
        new (): HTMLQuickviewComponentElement;
    };
    interface HTMLElementTagNameMap {
        "quickview-component": HTMLQuickviewComponentElement;
    }
}
declare namespace LocalJSX {
    interface QuickviewComponent {
    }
    interface IntrinsicElements {
        "quickview-component": QuickviewComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "quickview-component": LocalJSX.QuickviewComponent & JSXBase.HTMLAttributes<HTMLQuickviewComponentElement>;
        }
    }
}
