/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomPerPage {
        "choicesDisplayed": string;
        "initialChoice"?: number;
    }
}
declare global {
    interface HTMLCustomPerPageElement extends Components.CustomPerPage, HTMLStencilElement {
    }
    var HTMLCustomPerPageElement: {
        prototype: HTMLCustomPerPageElement;
        new (): HTMLCustomPerPageElement;
    };
    interface HTMLElementTagNameMap {
        "custom-per-page": HTMLCustomPerPageElement;
    }
}
declare namespace LocalJSX {
    interface CustomPerPage {
        "choicesDisplayed": string;
        "initialChoice"?: number;
    }
    interface IntrinsicElements {
        "custom-per-page": CustomPerPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-per-page": LocalJSX.CustomPerPage & JSXBase.HTMLAttributes<HTMLCustomPerPageElement>;
        }
    }
}
